name: habitonic
description: Habitonic - Habit Tracker

publish_to: "none"

version: 1.0.0+8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.8
  flutter_svg_provider: ^1.0.7
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  percent_indicator: ^4.0.1
  get_it: ^7.2.0
  path_provider: ^2.0.10
  equatable: ^2.0.3
  intl: ^0.19.0
  dartz: ^0.10.1
  fimber: ^0.6.6
  sizer: ^2.0.15
  just_the_tooltip: ^0.0.11+2
  fading_edge_scrollview: ^4.1.1
  timeago: ^3.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  freezed: ">=1.0.0 <=2.0.3"
  freezed_annotation: ">=1.0.0 <=2.0.3"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/dev/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/dev/
    - assets/icons/
    - assets/icons/habits/
    - assets/icons/flags/
    - assets/images/
    - assets/flares/
    - assets/i18n/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

    - family: Noto Sans
      fonts:
        - asset: assets/fonts/noto_sans/NotoSans-Regular.ttf
        - asset: assets/fonts/noto_sans/NotoSans-Bold.ttf
          weight: 700
